platform :ios, '8.0'
target 'teacher' do
pod 'YTKNetwork'
pod 'JSONModel'
pod 'Masonry'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'YTKKeyValueStore'
pod 'MJRefresh','~> 2.4.11'
pod 'RongCloudIMKit', '~> 2.4.0'
pod ‘SDWebImage’, '~> 3.7.2'
pod 'ZYQAssetPickerController',  '~> 1.0.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
pod 'MLLabel','~> 1.9.0'
pod 'DFCommon', '~> 1.3.9'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'MLLabel', '~> 1.9.0'
pod 'MMPopupView', '~> 1.7.1'
pod 'ODRefreshControl', '~> 1.2'
pod 'SVProgressHUD', '~> 2.0.2'
pod 'TZImagePickerController', '~> 1.1.3'
pod 'YLGIFImage', '~> 0.11'
pod 'DFTimelineView'
end


